Fix issue: Burr integration by updating fetch_node.py
Before Burr integration would cause an error in fetch:
ValueError: Action Fetch attempted to write to keys {'original_html'} that it did not declare. It declared: (['doc'])!